# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8 
        
      - name: Build but skip tests
        run: mvn clean package
        
      - name: Current Working Directory
        run: pwd
        
      - name: Get version
        run: |
          VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "::set-output name=version::$VERSION"
        id: get_version
        
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@master
        with:
          name: bahmnicore-omod-0.92-SNAPSHOT
          path: ./validator/target/initializer-validator-2.1.0-SNAPSHOT.jar
          retention-days: 5
